### ISSUE TITLE
Valid token, but API that requires scope I don't have:

### ISSUE THREAD

**Issue by josephhr** [fillup/php-oauth-saml-demo#1]
Dear Phillip,

I am trying to test the demo using Vagrant. However, in the final message (after being logged in, debug page), I get "Valid token, but API that requires scope I don't have"
Array
(
    [success] => false
    [error] => You do not have the required scope: notallowed.
    [code] => 403
)

"Invalid Access Token Request":
Array
(
    [success] => false
    [error] => invalid_token, the access token is not active (Bearer invalidtoken)
    [code] => 401
)

Do you any clue about this issue.

Thanks in advance.

Best regards.

**Comment by fillup** [comment]
Hi @josephhr that is actually correct. Those last two items on the example page are testing/confirming that you get those errors when it tries to request a scope it doesnt have access to or if you use an invalid token. So getting those messages is good :-)

**Comment by josephhr** [comment]
Thank you so much.

Best regards.
