### ISSUE TITLE
Configuration without Vagrant

### ISSUE THREAD

**Issue by josephhr** [fillup/php-oauth-saml-demo#2]
Dear Philip,

I am trying to install the demo scenario without vagrant. Basically, I follow the steps that are provided in the provision-shared.sh file adapted for local machine. I put everything into /var/www folder, run composer, etc. For apache configuration I have created a file for each entity appserver.conf, appclient.conf, php-oauth.conf and simplesamlphp.conf in conf-enabled folder. So for example the appclient is accesible via http://localhost/appclient/public/index.php. Actually, all entities are accessible, however if I try to do clic on any tab, for example About, I get a Not Found message from the browser. Of couse, the same happens when I try to clic on Login. Do you have any clue about this issue?

Best regards

**Comment by fillup** [comment]
What is the link for the other tab? I'm wondering if the app isnt happy about being in a subfolder path like that. Does the main page show all the debug info like it does in vagrant?

**Comment by josephhr** [comment]
Thank you so much for your answer. Finally, I installed everything using virtual hosts in the same way that using the vagrant machine, and it worked perfectly.

Thanks again

Best regards.

**Comment by fillup** [comment]
Great, glad to hear its working :-)
